CREATE VIEW STORE_AND_EMP_INFO_VIEW AS
SELECT s.STORE_NAME, s.EMAIL, s.CITY, s.STREET, e.EMP_ID, e.FIRST_NAME, 
		e.LAST_NAME, e.PHONE_NUMBER
FROM STORE s
JOIN EMPLOYEE e ON s.STORE_ID = e.STORE_ID;
GO

CREATE VIEW ORDER_AND_CUS_INFO_VIEW AS
SELECT c.ACCOUNT_ID, o.ORDER_ID, o.ORDER_DATE, od.PRICE_PER_PRODUCT, od.QUANTITY
FROM ORDER_DETAIL od
JOIN CUSTOMER c ON od.CUS_ID = c.CUS_ID
JOIN ORDERS o ON .ORDER_ID = od.ORDER_ID;
GO